IF "%LOG_DISABLED%" == "" echo %REPO_TO_CLONE%: about to copy %GIT_SYNCH_HOME%\%REPOSITORIES_TO_REPLICATE%\%REPO_BUNDLE% %ISE_DROP%\%REPO_BUNDLE%.tmp
copy /B %GIT_SYNCH_HOME%\%REPOSITORIES_TO_REPLICATE%\%REPO_BUNDLE% %ISE_DROP%\%REPO_BUNDLE%.tmp 2>&1
IF "%LOG_DISABLED%" == "" echo %REPO_TO_CLONE%: about to rename %ISE_DROP%\%REPO_BUNDLE%.tmp %REPO_BUNDLE%
rename %ISE_DROP%\%REPO_BUNDLE%.tmp %REPO_BUNDLE%  2>&1
IF "%LOG_DISABLED%" == "" echo %REPO_TO_CLONE%: about to move %GIT_SYNCH_HOME%\%REPOSITORIES_TO_REPLICATE%\%REPO_BUNDLE% %GIT_SYNCH_HOME%\%REPOSITORIES_TO_REPLICATE%\%REPO_TO_CLONE%
move /Y %GIT_SYNCH_HOME%\%REPOSITORIES_TO_REPLICATE%\%REPO_BUNDLE% %GIT_SYNCH_HOME%\%REPOSITORIES_TO_REPLICATE%\%REPO_TO_CLONE%  2>&1